export const mockData = {
  id: 123,
  title: "Modern Apartment in Singapore CBD",
  apartmentsInfo:
    "Bright and spacious apartment with stunning city views, located in the heart of Singapore's Central Business District. Close to restaurants, shops, and public transportation. Looking for a friendly and respectful roommate!",
  cost: 2500,
  deposit: 3000,
  minAmountOfCommunalService: 200,
  maxAmountOfCommunalService: 350,
  arriveDate: "2025-05-15",
  typeOfHousing: "Apartment",
  quantityOfRooms: 3,
  areaOfTheApartment: 90,
  numberOfFloor: 15,
  maxFloorInTheBuilding: 38,
  howManyPeopleLiveInThisApartment: 1,
  numberOfPeopleAreYouAccommodating: 1,
  region: "Singapore",
  district: "Central Business District",
  microDistrict: "Marina Bay",
  preferences: ["Cleanliness", "No smoking", "No pets", "Professional"],
  photos: [
    { id: 1, url: "/picturas/sing1.jpg" },
    { id: 2, url: "/picturas/sing2.jpg" },
    { id: 3, url: "/picturas/sing3.jpg" },
    { id: 4, url: "/picturas/sing4.jpg" },
    { id: 5, url: "/picturas/sing5.jpg" },
    { id: 6, url: "/picturas/sing6.jpg" },
  ],
  user: {
    firstName: "Michael",
    lastName: "Wong",
    profilePhoto: null,
  },
  phoneNumber: "6590123456",
};
